version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  test_db:
    image: postgres:13
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_TEST_HOST_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_TEST_USER}
      - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}

  web:
    build:
      context: .
      args:
        UID: ${DOCKER_UID}
        GID: ${DOCKER_GID}
    user: ${DOCKER_UID}:${DOCKER_GID}
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    volumes:
      - .:/app
    ports:
      - "${FASTAPI_RUN_PORT}:8000"
      - 5678:5678
    env_file:
      - .env
    depends_on:
      - db
      - test_db

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
  test_postgres_data:
