"""first migration

Revision ID: 077a1b7fc10b
Revises: 
Create Date: 2023-12-11 16:31:23.374087

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '077a1b7fc10b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('html_body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('email_variables',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('variable', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates_email_variables',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('email_template_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('email_variable_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.ForeignKeyConstraint(['email_template_id'], ['email_templates.id'], ),
    sqlmodel.ForeignKeyConstraint(['email_variable_id'], ['email_variables.id'], ),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permissions',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('role_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('permission_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sqlmodel.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sqlmodel.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sqlmodel.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sqlmodel.Column('country_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sqlmodel.Column('active', sqlmodel.Boolean(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('deleted_at', sqlmodel.DateTime(), nullable=True),
    sqlmodel.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sqlmodel.Column('id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('user_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('role_id', sqlmodel.Integer(), nullable=False),
    sqlmodel.Column('created_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.Column('updated_at', sqlmodel.DateTime(), nullable=False),
    sqlmodel.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sqlmodel.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sqlmodel.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('users')
    op.drop_table('roles_permissions')
    op.drop_table('email_templates_email_variables')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('email_variables')
    op.drop_table('email_templates')
    op.drop_table('countries')
    # ### end Alembic commands ###
